### ISSUE TITLE
Down layer doesn't appear to be double sided

### ISSUE THREAD

**Issue by cbeust** [Cride5/visualcube#6]
[This cube](http://cube.crider.co.uk/visualcube.php?fmt=svg&size=200&r=y15x30&cc=n&co=30&fo=35&fc=ttttttttttttrrrtrrttttbbrbtwwtwwwwwwtttootoobtttgggggg) seen from below shows that the D layer is white.

![image](https://cloud.githubusercontent.com/assets/92322/23237511/92842a5c-f912-11e6-92b8-19509f992221.png)

However, that same cube seen from above shows the D layer grey instead of white:

![image](https://cloud.githubusercontent.com/assets/92322/23237524/a2dc55c8-f912-11e6-8c9c-4bce7f6bd00f.png)

[Buggy cube](http://cube.crider.co.uk/visualcube.php?fmt=svg&size=200&r=y15x-50&cc=n&co=30&fo=35&fc=ttttttttttttrrrtrrttttbbrbtwwtwwwwwwtttootoobtttgggggg).

**Comment by Cride5** [comment]
This is because the white tiles on the underside are the same colour as the background. There is nothing behind them to show their colour.

Consider this cube:
![Green Cube](http://cube.crider.co.uk/visualcube.php?fmt=svg&size=200&r=y15x-50&cc=n&co=30&fo=35&fc=ttttttttttttrrrtrrttttbbrbtwwtwwwwwwtttootoobtttgggggg&bg=green)

This time you can see the white but not the green.

**Comment by cbeust** [comment]
Doh, of course. I feel silly.

Thanks!
